dist: xenial
language: python
python:
  - '3.7.1'
install:
  - if [[ -f ./requirements.txt ]]; then
      pip install -r ./requirements.txt;
    fi
script:
  - find . -type f -name "*.py" | xargs python -u
